import type { Metadata } from "next";
import "./globals.css";
import CustomProvider from "./components/CustomProvider";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Wedding of Tiffany and Jared",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.className} antialiased`}>
        <CustomProvider>{children}</CustomProvider>
      </body>
    </html>
  );
}
